# Generated by Django 3.2.7 on 2021-09-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210915_0145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
