# Generated by Django 3.2.7 on 2021-09-13 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_like_notification_notificationlistener'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationlistener',
            old_name='channel_name',
            new_name='notification_group_name',
        ),
    ]
